# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, unique=True, verbose_name='URL')),
                ('attachment_id', models.CharField(max_length=128, verbose_name='Attachment ID')),
            ],
            options={
                'verbose_name': 'Facebook Attachment',
                'verbose_name_plural': 'Facebook Attachments',
            },
        ),
    ]
