# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.CharField(max_length=640, verbose_name='Text')),
                ('link_one_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Link 1 - Titel')),
                ('link_one_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Link 1 - URL')),
                ('link_two_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Link 2 - Titel')),
                ('link_two_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Link 2 - URL')),
                ('link_three_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Link 3 - Titel')),
                ('link_three_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Link 3 - URL')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlicht am')),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
            },
        ),
    ]
