# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='link_one_title',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_one_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_three_title',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_three_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_two_title',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_two_url',
        ),
        migrations.AddField(
            model_name='entry',
            name='link_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='link_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='link_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry'),
        ),
    ]
