# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170419_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='short_title',
            field=models.CharField(default='', help_text='Wird auf den Link-Buttons angezeigt (max. 20 Zeichen)', max_length=20, verbose_name='Kurzer Titel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='link_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry', verbose_name='Link 1'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='link_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry', verbose_name='Link 3'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='link_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry', verbose_name='Link 2'),
        ),
    ]
