# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170419_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='User ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hinzugefügt am')),
            ],
            options={
                'verbose_name': 'Facebook User',
                'verbose_name_plural': 'Facebook User',
            },
        ),
    ]
