# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170425_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Entry', verbose_name='Link 1'),
        ),
    ]
