# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170428_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='web_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(help_text='Wenn Link max. 80 Zeichen!', max_length=640, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(help_text='Wenn Link max. 80 Zeichen!', max_length=200, verbose_name='Titel'),
        ),
    ]
