# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20170502_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Übeschrift')),
                ('intro_text', models.CharField(max_length=200, verbose_name='Intro-Text')),
                ('intro_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang Intro')),
                ('intro_media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('intro_attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('first_question', models.CharField(blank=True, max_length=20, null=True, verbose_name='Erste Frage')),
                ('first_text', models.CharField(blank=True, max_length=600, null=True, verbose_name='Erster Text')),
                ('first_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Erster Medien-Anhang')),
                ('first_media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('first_attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('second_question', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zweite Frage')),
                ('second_text', models.CharField(blank=True, max_length=600, null=True, verbose_name='Zweiter Text')),
                ('second_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Zweiter Medien-Anhang')),
                ('second_media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('second_attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('third_question', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dritte Frage')),
                ('third_text', models.CharField(blank=True, max_length=600, null=True, verbose_name='Dritter Text')),
                ('third_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dritter Medien-Anhang')),
                ('third_media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('third_attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Für morgens auf 6:00, für abends auf 18:00 timen (Uhr-Symbol)', verbose_name='Veröffentlicht am')),
                ('published', models.BooleanField(default=False, verbose_name='Veröffentlicht?')),
                ('breaking', models.BooleanField(default=False, help_text='Breaking-News werden außerhalb der regelmäßigen Push-Zyklen zu der angegebenen Zeit gesendet', verbose_name='Breaking?')),
                ('delivered', models.BooleanField(default=False, help_text='Wurde der Push bereits vom Bot versendet? Nur relevant für Breaking-News.', verbose_name='Versendet?')),
            ],
            options={
                'verbose_name': 'Push-Nachricht',
                'verbose_name_plural': 'Push-Nachrichten',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(help_text='Der Eingabetext des Nutzers', max_length=128, unique=True, verbose_name='Eingabe')),
                ('output', models.CharField(help_text='Die Antwort, die der Bot auf die Eingabe geben soll', max_length=640, verbose_name='Antwort')),
            ],
            options={
                'verbose_name': 'Wiki-Eintrag',
                'verbose_name_plural': 'Wiki-Einträge',
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_one',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_three',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='link_two',
        ),
        migrations.RemoveField(
            model_name='facebookuser',
            name='name',
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='State'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
