# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20170719_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='attachment_id',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='output',
            field=models.CharField(blank=True, help_text='Die Antwort, die der Bot auf die Eingabe geben soll', max_length=640, null=True, verbose_name='Antwort'),
        ),
    ]
