# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170904_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hinweis: Wird nicht ausgespielt', max_length=128, unique=True, verbose_name='Titel')),
                ('content', models.CharField(blank=True, help_text='Text der Info', max_length=600, null=True, verbose_name='Inhalt')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
            ],
            options={
                'verbose_name_plural': 'Infos',
                'verbose_name': 'Info',
            },
        ),
    ]
